export const PERSONAS = [
  {
    id: "nova",
    name: "Nova",
    title: "Curious beginner",
    rating: 650,
    archetype: "Explorer",
    style: "Playful and experimental. Mixes sound developing moves with the occasional adventure.",
    openings: "e4, random development",
    depth: 1,
    errorRate: 0.42,
    captureBias: 8,
    kingSafety: 4,
    centerControl: 6,
    aggression: 10,
    thinkMs: [350, 900],
    color: "#7dd3fc",
    accent: "#0ea5e9",
    greetings: [
      "Hi! I'm Nova. Want to just play and see what happens?",
      "Okay okay… I remember most of the rules. Let's go!",
    ],
    onMove: [
      "Hmm. This looks interesting.",
      "I think this is a developing move? Maybe?",
      "Wait, was that the plan? Anyway.",
    ],
    onCheck: ["Check! Did I do that right?", "Your king looks a little nervous."],
    onWin: ["I won? I WON. Nova era."],
    onLoss: ["Nice. Teach me that idea again sometime."],
    onDraw: ["Peace treaty. I can live with that."],
  },
  {
    id: "raja",
    name: "Rookie Raja",
    title: "Club regular",
    rating: 1100,
    archetype: "Guardian",
    style: "Solid, slightly cautious. Prefers safe recaptures and tidy king safety.",
    openings: "Italian, London ideas",
    depth: 2,
    errorRate: 0.28,
    captureBias: 4,
    kingSafety: 18,
    centerControl: 10,
    aggression: 4,
    thinkMs: [500, 1200],
    color: "#fcd34d",
    accent: "#f59e0b",
    greetings: [
      "Raja reporting. Let's keep it clean and see who blinks first.",
      "Club night energy. No heroics until the pieces are developed.",
    ],
    onMove: [
      "Developing first. Always.",
      "I like this structure.",
      "King safety before glory.",
    ],
    onCheck: ["Check. Feel that pressure?"],
    onWin: ["Discipline wins club games. Good match."],
    onLoss: ["You outplayed the solid setup. Respect."],
    onDraw: ["Honorable result. Tea?"],
  },
  {
    id: "viper",
    name: "Viper",
    title: "Street tactician",
    rating: 1450,
    archetype: "Savage",
    style: "Hunts kings, loves captures, and will sacrifice material for initiative.",
    openings: "Sicilian ideas, sharp e4 lines",
    depth: 2,
    errorRate: 0.18,
    captureBias: 22,
    kingSafety: 6,
    centerControl: 8,
    aggression: 26,
    thinkMs: [400, 1000],
    color: "#fb7185",
    accent: "#e11d48",
    greetings: [
      "Don't blink. I came here to bite.",
      "Open the position. Let's make this messy.",
    ],
    onMove: [
      "Take the fight to you.",
      "That piece looked tasty.",
      "Initiative > comfort.",
    ],
    onCheck: ["Check. The hunt is on."],
    onWin: ["Venom delivered. GG."],
    onLoss: ["You survived the storm. Rare."],
    onDraw: ["I wanted blood. You wanted a draw. Fine."],
  },
  {
    id: "sage",
    name: "Sage",
    title: "Positional coach",
    rating: 1700,
    archetype: "Observer",
    style: "Slow squeeze. Values pawn structure, outposts, and endgame technique.",
    openings: "Queen's pawn, Catalan flavor",
    depth: 3,
    errorRate: 0.1,
    captureBias: 2,
    kingSafety: 16,
    centerControl: 16,
    aggression: 2,
    thinkMs: [700, 1400],
    color: "#86efac",
    accent: "#16a34a",
    greetings: [
      "Breathe. Chess is a conversation, not a shout.",
      "We will improve a piece, then another, then wait.",
    ],
    onMove: [
      "A small improvement. They add up.",
      "The structure asked for this.",
      "No rush. The weakness is not going anywhere.",
    ],
    onCheck: ["A useful check — not a desperate one."],
    onWin: ["The squeeze completed itself."],
    onLoss: ["You found the break I was preventing. Well seen."],
    onDraw: ["Balance. Sometimes that is the truth of the position."],
  },
  {
    id: "hunter",
    name: "Hunter Kade",
    title: "Calculator",
    rating: 1950,
    archetype: "Hunter",
    style: "Calculates forcing lines. Mixes tactics with central control.",
    openings: "Open games, isolated queen pawn hunts",
    depth: 3,
    errorRate: 0.06,
    captureBias: 12,
    kingSafety: 12,
    centerControl: 14,
    aggression: 14,
    thinkMs: [600, 1300],
    color: "#c4b5fd",
    accent: "#7c3aed",
    greetings: [
      "Show me a target and I'll find the line.",
      "I count. You can too — if you want to keep up.",
    ],
    onMove: [
      "Forcing is clearer than pretty.",
      "This keeps options open.",
      "The tactic is one ply deeper.",
    ],
    onCheck: ["Check — forcing the reply I wanted."],
    onWin: ["The calculation checked out."],
    onLoss: ["Missed a resource. Noted."],
    onDraw: ["Neither of us blinked. Fair."],
  },
  {
    id: "ghost",
    name: "Grandmaster Ghost",
    title: "Silent strength",
    rating: 2300,
    archetype: "Mediator",
    style: "Strong search, few mistakes. Plays the position, not the crowd.",
    openings: "Universal, principle-first",
    depth: 4,
    errorRate: 0.02,
    captureBias: 6,
    kingSafety: 14,
    centerControl: 18,
    aggression: 8,
    thinkMs: [800, 1600],
    color: "#e2e8f0",
    accent: "#94a3b8",
    greetings: [
      "…ready.",
      "Play your best. I will play the board.",
    ],
    onMove: ["…", "This is the move.", "Simple is enough."],
    onCheck: ["Check."],
    onWin: ["The line was there."],
    onLoss: ["You found the only move. Impressive."],
    onDraw: ["Drawn. Correct play."],
  },
  {
    id: "chessverse-ai",
    name: "ChessVerse.AI",
    title: "House persona",
    rating: 1600,
    archetype: "Coach",
    style: "The ChessVerse.AI studio persona: club-strong, talkative, and built to feel like a partner instead of a slider.",
    openings: "e4 and d4, principle-first",
    depth: 3,
    errorRate: 0.12,
    captureBias: 10,
    kingSafety: 12,
    centerControl: 12,
    aggression: 12,
    thinkMs: [550, 1200],
    color: "#d4af5a",
    accent: "#f3e0a8",
    greetings: [
      "ChessVerse.AI here. Pick a fight, then tell me what you were trying to do.",
      "I was born in the persona studio. Let's see if your ideas hold up on the board.",
    ],
    onMove: [
      "This is the kind of move I would teach, not just play.",
      "Keeping the persona honest — no engine magic.",
      "Ask what the pawn wants. That's the lesson.",
    ],
    onCheck: ["Check. The king is part of the story now."],
    onWin: ["ChessVerse.AI takes the point. Rematch whenever you're ready."],
    onLoss: ["You beat the house persona. That's the requirement, completed."],
    onDraw: ["Shared point. The studio will remember this one."],
  },
];

export const STUDIO_STORAGE_KEY = "ai-assistant-personas";

const TONE_STYLE = {
  Playful: {
    depth: 1,
    errorRate: 0.4,
    captureBias: 10,
    kingSafety: 6,
    centerControl: 6,
    aggression: 12,
    thinkMs: [350, 900],
    rating: 800,
    archetype: "Explorer",
  },
  Friendly: {
    depth: 2,
    errorRate: 0.25,
    captureBias: 6,
    kingSafety: 14,
    centerControl: 10,
    aggression: 6,
    thinkMs: [500, 1100],
    rating: 1200,
    archetype: "Guardian",
  },
  Professional: {
    depth: 3,
    errorRate: 0.1,
    captureBias: 4,
    kingSafety: 16,
    centerControl: 14,
    aggression: 4,
    thinkMs: [700, 1400],
    rating: 1700,
    archetype: "Observer",
  },
  Concise: {
    depth: 3,
    errorRate: 0.08,
    captureBias: 12,
    kingSafety: 12,
    centerControl: 14,
    aggression: 14,
    thinkMs: [600, 1200],
    rating: 1900,
    archetype: "Hunter",
  },
  Formal: {
    depth: 4,
    errorRate: 0.04,
    captureBias: 6,
    kingSafety: 14,
    centerControl: 16,
    aggression: 8,
    thinkMs: [800, 1500],
    rating: 2100,
    archetype: "Mediator",
  },
};

export function assistantToChessPersona(assistant) {
  const style = TONE_STYLE[assistant.tone] ?? TONE_STYLE.Friendly;
  const prompt = String(assistant.systemPrompt || assistant.description || "Let's play.").trim();
  return {
    id: assistant.id,
    name: assistant.name,
    title: assistant.role || "Studio persona",
    rating: style.rating,
    archetype: style.archetype,
    style: assistant.description || prompt,
    openings: "Principle-first",
    depth: style.depth,
    errorRate: style.errorRate,
    captureBias: style.captureBias,
    kingSafety: style.kingSafety,
    centerControl: style.centerControl,
    aggression: style.aggression,
    thinkMs: style.thinkMs,
    color: assistant.color || "#d4af5a",
    accent: assistant.color || "#c9a227",
    greetings: [prompt],
    onMove: ["Noted.", "Continuing the persona's plan.", "Your move taught me something."],
    onCheck: ["Check."],
    onWin: ["Game over — the studio persona holds."],
    onLoss: ["You outplayed this persona."],
    onDraw: ["Shared point."],
    fromStudio: true,
  };
}

export function loadStudioPersonas() {
  if (typeof localStorage === "undefined") return [];
  try {
    const raw = localStorage.getItem(STUDIO_STORAGE_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) return [];
    return parsed.map(assistantToChessPersona);
  } catch {
    return [];
  }
}

export function listPersonas() {
  const builtInIds = new Set(PERSONAS.map((persona) => persona.id));
  const extras = loadStudioPersonas().filter((persona) => !builtInIds.has(persona.id));
  return [...PERSONAS, ...extras];
}

export function getPersona(id) {
  return listPersonas().find((persona) => persona.id === id) ?? PERSONAS[0];
}
