export const PERSONAS = [
  {
    id: "nova",
    name: "Nova",
    title: "Curious beginner",
    rating: 650,
    archetype: "Explorer",
    style: "Playful and experimental. Mixes sound developing moves with the occasional adventure.",
    openings: "e4, random development",
    depth: 1,
    errorRate: 0.42,
    captureBias: 8,
    kingSafety: 4,
    centerControl: 6,
    aggression: 10,
    thinkMs: [350, 900],
    color: "#7dd3fc",
    accent: "#0ea5e9",
    greetings: [
      "Hi! I'm Nova. Want to just play and see what happens?",
      "Okay okay… I remember most of the rules. Let's go!",
    ],
    onMove: [
      "Hmm. This looks interesting.",
      "I think this is a developing move? Maybe?",
      "Wait, was that the plan? Anyway.",
    ],
    onCheck: ["Check! Did I do that right?", "Your king looks a little nervous."],
    onWin: ["I won? I WON. Nova era."],
    onLoss: ["Nice. Teach me that idea again sometime."],
    onDraw: ["Peace treaty. I can live with that."],
  },
  {
    id: "raja",
    name: "Rookie Raja",
    title: "Club regular",
    rating: 1100,
    archetype: "Guardian",
    style: "Solid, slightly cautious. Prefers safe recaptures and tidy king safety.",
    openings: "Italian, London ideas",
    depth: 2,
    errorRate: 0.28,
    captureBias: 4,
    kingSafety: 18,
    centerControl: 10,
    aggression: 4,
    thinkMs: [500, 1200],
    color: "#fcd34d",
    accent: "#f59e0b",
    greetings: [
      "Raja reporting. Let's keep it clean and see who blinks first.",
      "Club night energy. No heroics until the pieces are developed.",
    ],
    onMove: [
      "Developing first. Always.",
      "I like this structure.",
      "King safety before glory.",
    ],
    onCheck: ["Check. Feel that pressure?"],
    onWin: ["Discipline wins club games. Good match."],
    onLoss: ["You outplayed the solid setup. Respect."],
    onDraw: ["Honorable result. Tea?"],
  },
  {
    id: "viper",
    name: "Viper",
    title: "Street tactician",
    rating: 1450,
    archetype: "Savage",
    style: "Hunts kings, loves captures, and will sacrifice material for initiative.",
    openings: "Sicilian ideas, sharp e4 lines",
    depth: 2,
    errorRate: 0.18,
    captureBias: 22,
    kingSafety: 6,
    centerControl: 8,
    aggression: 26,
    thinkMs: [400, 1000],
    color: "#fb7185",
    accent: "#e11d48",
    greetings: [
      "Don't blink. I came here to bite.",
      "Open the position. Let's make this messy.",
    ],
    onMove: [
      "Take the fight to you.",
      "That piece looked tasty.",
      "Initiative > comfort.",
    ],
    onCheck: ["Check. The hunt is on."],
    onWin: ["Venom delivered. GG."],
    onLoss: ["You survived the storm. Rare."],
    onDraw: ["I wanted blood. You wanted a draw. Fine."],
  },
  {
    id: "sage",
    name: "Sage",
    title: "Positional coach",
    rating: 1700,
    archetype: "Observer",
    style: "Slow squeeze. Values pawn structure, outposts, and endgame technique.",
    openings: "Queen's pawn, Catalan flavor",
    depth: 3,
    errorRate: 0.1,
    captureBias: 2,
    kingSafety: 16,
    centerControl: 16,
    aggression: 2,
    thinkMs: [700, 1400],
    color: "#86efac",
    accent: "#16a34a",
    greetings: [
      "Breathe. Chess is a conversation, not a shout.",
      "We will improve a piece, then another, then wait.",
    ],
    onMove: [
      "A small improvement. They add up.",
      "The structure asked for this.",
      "No rush. The weakness is not going anywhere.",
    ],
    onCheck: ["A useful check — not a desperate one."],
    onWin: ["The squeeze completed itself."],
    onLoss: ["You found the break I was preventing. Well seen."],
    onDraw: ["Balance. Sometimes that is the truth of the position."],
  },
  {
    id: "hunter",
    name: "Hunter Kade",
    title: "Calculator",
    rating: 1950,
    archetype: "Hunter",
    style: "Calculates forcing lines. Mixes tactics with central control.",
    openings: "Open games, isolated queen pawn hunts",
    depth: 3,
    errorRate: 0.06,
    captureBias: 12,
    kingSafety: 12,
    centerControl: 14,
    aggression: 14,
    thinkMs: [600, 1300],
    color: "#c4b5fd",
    accent: "#7c3aed",
    greetings: [
      "Show me a target and I'll find the line.",
      "I count. You can too — if you want to keep up.",
    ],
    onMove: [
      "Forcing is clearer than pretty.",
      "This keeps options open.",
      "The tactic is one ply deeper.",
    ],
    onCheck: ["Check — forcing the reply I wanted."],
    onWin: ["The calculation checked out."],
    onLoss: ["Missed a resource. Noted."],
    onDraw: ["Neither of us blinked. Fair."],
  },
  {
    id: "ghost",
    name: "Grandmaster Ghost",
    title: "Silent strength",
    rating: 2300,
    archetype: "Mediator",
    style: "Strong search, few mistakes. Plays the position, not the crowd.",
    openings: "Universal, principle-first",
    depth: 4,
    errorRate: 0.02,
    captureBias: 6,
    kingSafety: 14,
    centerControl: 18,
    aggression: 8,
    thinkMs: [800, 1600],
    color: "#e2e8f0",
    accent: "#94a3b8",
    greetings: [
      "…ready.",
      "Play your best. I will play the board.",
    ],
    onMove: ["…", "This is the move.", "Simple is enough."],
    onCheck: ["Check."],
    onWin: ["The line was there."],
    onLoss: ["You found the only move. Impressive."],
    onDraw: ["Drawn. Correct play."],
  },
];

export function getPersona(id) {
  return PERSONAS.find((persona) => persona.id === id) ?? PERSONAS[0];
}
